AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

MethodLength:
  Max: 25

CyclomaticComplexity:
  Max: 7

ParameterLists:
  Enabled: false

Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: true
  Exclude:
    - metadata.rb
